### ISSUE TITLE
Restore missing plugin opcode libraries

### ISSUE THREAD

**Issue by ST-Music** [gogins/csound-android#19]
I get the same error with both opcodes:

https://www.dropbox.com/scl/fi/s1e84t0gguc2v56trr9dn/Screenshot_20230827_220514.jpg?rlkey=h88072vavvy5l5r7yys3waiaf&dl=0

I have tried the manual example: 
https://csound.com/docs/manual/directory.html

as well as:
<CsoundSynthesizer>
<CsOptions>
-odac
</CsOptions>
<CsInstruments>

;browse for text files in current directory
instr 1
iCnt init 0
SFilenames[] directory "/storage/emulated/0/Music/samples/", ".wav"
iNumberOfFiles lenarray SFilenames

until iCnt>=iNumberOfFiles do
	printf_i "Filename = %s \n", 1, SFilenames[iCnt]
	iCnt = iCnt+1
od
endin

</CsInstruments>
<CsScore>
i1 0 1
</CsScore>
</CsoundSynthesizer>

and changing the path to:
"/storage/emulated/0/Music/samples",  ".wav"

(no backslash following samples)

I tested with the previous version & either path will work.

Side note: I have no difficulty loading single samples from directories now so that's working great.

**Comment by gogins** [comment]
I have reproduced the directory bug. It looks like the opcode does not exist in the Android build. I am investigating.

**Comment by ST-Music** [comment]
Thanks for the reply Michael.

**Comment by gogins** [comment]
Indeed, the directory opcode is in the same plugin library as the ftsamplebank opcode. Rory Walsh wrote this. The android build system does not build or package this library. It should be easy to fix. There are a few other plugins like this that might also be missing and could be put back.

**Comment by ST-Music** [comment]
Odd as it was included in the previous build but good to hear you can
hopefully resolve this. Then I can get back to putting it thru it's paces.
Thanks again.

**Comment by gogins** [comment]
This situation was caused a few years ago when the core Csound developers removed a number of plugin opcodes from the Csound GitHub repository, and changed the way that the remaining opcodes are built. The current situation is clearly explained in [`Opcodes/CMakeLists.txt`](https://github.com/csound/csound/blob/master/Opcodes/CMakeLists.txt).

By the way, although this change involved removing a number of my own contributions from the Csound repository, I nevertheless agree that it was a good idea. Csound was becoming difficult to maintain due to increasing external dependencies, lack of manpower, dislike of C++, and lack of C++ expertise. I think it is **_very_** important to keep maintaining and improving Csound, and there aren't enough people involved.

The Csound for Android build system was already building some of these plugins. The following is a list of **_all_** plugin opcode libraries built by the standard Csound build system, with notes as to their current status for Android. 

- [x] make_plugin(ampmidid ampmidid.cpp). Now building for Android.			
- [x] make_plugin(arrayops arrayops.cpp). Now building for Android.					
- [x] make_plugin(bformdec2 bformdec2.cpp). Now building for Android.		
- [ ] make_plugin(control control.c). Not portable, will not be built for Android.				
- [ ] make_plugin(deprecated deprecated.c). Contains a number of deprecated opcodes that I have chosen not to build for Android.				
- [x] make_plugin(doppler doppler.cpp). Already built for Android.				
- [ ] make_plugin(dssi4cs "${dssi_SRC}" dl). Not portable, will not be built for Android.				
- [x] make_plugin(fractalnoise tl/fractalnoise.cpp). Now building for Android.					
- [x] make_plugin(ftsamplebank ftsamplebank.cpp). Now building for Android.					
- [ ] make_plugin(joystick linuxjoystick.c). Not portable, will not be built for Android.				
- [x] make_plugin(lfsr lfsr.cpp). Now building for Android.			
- [x] make_plugin(mixer mixer.cpp). Now building for Android.				
- [x] make_plugin(osc OSC.c). Already built for Android.				
- [x] make_plugin(padsynth padsynth_gen.cpp). Now building for Android.					
- [x] make_plugin(pvsops pvsops.cpp). Now building for Android.					
- [x] make_plugin(scansyn "${scansyn_SRCS}" ${MATH_LIBRARY}). Already built for Android.				
- [x] make_plugin(signalflowgraph signalflowgraph.cpp). Already built for Android.				
- [x] make_plugin(trigenvsegs trigEnvSegs.cpp). Now building for Android.			
- [ ] make_plugin(urandom urandom.c). Not portable, will not be built for Android.

**Comment by gogins** [comment]
The directory opcode now works.

**Comment by ST-Music** [comment]
That's great, let me know when to test the next beta (with a link).

Thanks!

**Comment by gogins** [comment]
https://github.com/gogins/csound-android/releases/tag/v36
