### ISSUE TITLE
The Csound for Android app crashes when the file open chooser starts on HTC U11 (OS: Android 9) 

### ISSUE THREAD

**Issue by gogins** [gogins/csound-android#2]
This issue was brought to my attention by Karin Daum.

**Comment by gogins** [comment]
I have rewritten the permissions handling in the Csound for Android app. I have added read and write URI permissions to the _New_, _Open_, and _Save as..._ file choosers. I have added `BODY_SENSORS` and `READ_EXTERNAL_STORAGE` permissions to the app manifest. I check relevant permissions every time they may be required. These changes have apparently not solved Karin's problem.

**Comment by gogins** [comment]
I have created an  Android Virtual Device to emulate the HTC U11 Life, based on the SDK 29 Android 10 image for x86_64. The Csound for Android app runs fine on this emulator with or without the URI permissions. 

Although I am now debugging on the same operating system as Karin, I cannot reproduce Karin's problem. I can open, save, and reopen files on the device storage.

**Comment by gogins** [comment]
Is this relevant? https://www.xda-developers.com/android-oreo-background-location-whitelist/

This post contains instructions for using ADB to whitelist an app.

**Comment by gogins** [comment]
Also, the logging of device admin calls suggests that Karin's device might actually belong not to her personally but rather to an institution, and this could conceivably cause a problem. My emulator for her device does not show these device admin calls.

If that is the case, then it may be necessary for Karin to have her institution whitelist the Csound for Android app.

**Comment by MarieCurie13** [comment]
> This issue was brought to my attention by Karin Daum.



> This issue was brought to my attention by Karin Daum.

On my HTC U11 the app stops unexpectedly when tapping on 'Open', 'New', 'Write' and 'Settings'. The examples can be played as far as I can see. The following happens when touching these buttons: The child activities are starting as expected, i.e. a new window is popping up, e.g. the directory 'Music' when 'Open' was touched, but closes after a fraction of a second.

I connected my phone to my laptop to have a look with AndroidStudio to the messages with Logcat. (I was so far not able to get the app built by myself, therefore I use the app from here (or initially from google play store). 
I can see, that the ActivityManager starts the activity launched via startActivityForResult in the CsoundAppActivity. I also see the related ActivityTrigger messages **but the printout from the onActivityResult message (more precisely from the checkOnePermission method implemented by Mike to find out what is going on) is missing**. There is no traceback dump you normally get when your app crashes. 

as an example you find the Logcat messages related to Csound when tapping on Settings attached.
[logcut.txt](https://github.com/gogins/csound-android/files/4550780/logcut.txt)

Initially I though, the problem may be due to the 

'E/ActivityTrigger: activityStartTrigger: not whiteListedcom.csounds.Csound6/com.csounds.Csound6.SettingsActivity/26' 

but similar messages I get also from other app which apparently work as expected.

**Comment by gogins** [comment]
The whitelisting may succeed for another app that does not try to open a file chooser. We could identify the cause here if it is possible to:

1. Try the Csound app on another U11 that is not managed.
2. Try another app that does not open any choosers on your U11.

In the meantime, I am trying to find more information on this. This management program (https://amtelnet.com/solutions/mobile-device-management/android-device-management/) has a fairly granular set of features to enable/disable for Android. Of course I do not really know if your U11 is managed but it seems likely. Of course I do not know the policies in force if it is managed. And  of course I do not know which management system, if any, is being used on your device.

However, this warning message in logcat strongly implies that a policy violation has caused this crash (from an earlier email):
```
04-28 18:25:48.472 3072-3749/? W/HtcSystemUPManager: HtcSystemUPHandler The policy is disabled. AppId: activity_history, category: launch
```
I was able to find a few pastebins with similar warning messages followed by crashes in other apps. **That is the strongest implication that a policy violation is the problem**. But I am looking at other funny looking messages in the logcat trace.

**Comment by MarieCurie13** [comment]
I think the 'not whiteListed’ is unlikely to be the problem. I tried some other apps (some most likely use startActivity only and another one uses most likely startActivityForResult). I always get the ’not whiteListed’ messages but the apps behave normal. These apps do not open any Chooser. 

Btw. ’Settings’ in Csound also does not use the chooser. The SettingsActivity class is part of the Csound app.

The phone is my personal phone and I do not have access to another U11.

**Comment by gogins** [comment]
Thanks for the information. I'll keep looking...

-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by gogins** [comment]
I can't pursue this without the help of Karin or another U11 user, so I'm closing this now but may re-open it later.
